{
 "title": "AIBrix Engine Dashboard (TRT-LLM)",
 "description": "Monitoring TRT-LLM Inference Server",
 "tags": [
  "aibrix",
  "model",
  "trtllm"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "model_name",
    "label": "model_name",
    "query": {
     "query": "label_values(trtllm_request_success_total,model_name)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(trtllm_request_success_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(trtllm_request_success_total{model_name=~\"$model_name\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Success Request Count"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "heatmap",
   "description": "Heatmap of end to end request latency in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (increase(trtllm_e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "heatmap",
   "description": "Heatmap of time to first token latency in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(le) (increase(trtllm_time_to_first_token_seconds_bucket{model_name=~\"$model_name\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "heatmap",
   "description": "Heatmap of time per output token latency in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(le) (increase(trtllm_time_per_output_token_seconds_bucket{model_name=~\"$model_name\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Queue Time",
   "type": "heatmap",
   "description": "Heatmap of request queue time in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(le) (increase(trtllm_request_queue_time_seconds_bucket{model_name=~\"$model_name\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "KV Cache Utilization",
   "type": "timeseries",
   "description": "KV Cache utilization percentage.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "trtllm_kv_cache_utilization{model_name=~\"$model_name\", job=~\"$job\"}",
     "legendFormat": "KV Cache Utilization"
    }
   ]
  },
  {
   "title": "KV Cache Hit Rate",
   "type": "timeseries",
   "description": "KV cache hit rate.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "trtllm_kv_cache_hit_rate{model_name=~\"$model_name\", job=~\"$job\"}",
     "legendFormat": "KV Cache Hit Rate"
    }
   ]
  }
 ]
}